### ISSUE TITLE
Error NU1202	Package Google.Ads.GoogleAds 18.1.0 is not compatible with net8.0 (.NETCoreApp,Version=v8.0)

### ISSUE THREAD

**Issue by AnthonyGiretti** [googleads/google-ads-dotnet#557]
Hi , I'm working with .NET 8. Unfortunately version 18.1.0 (same for 19.0.0)  of the Nuget package does not support .NET 8 while **17.1.0 DOES** and I need to move on V16 GoogleAds. The sunset of V14 is in May. V15 is not worth it; its sunset is in September 2024.

Will you allow .NET 8 soon? It's blocking us.

![image](https://github.com/googleads/google-ads-dotnet/assets/21200167/55fff72b-00f3-4cb0-b7a5-176b52958d37)

Thanks

**Comment by Raibaz** [comment]
Ah, you're right, support for net8.0 was supposed to be added in 19.0.0 but it fell through the cracks, I just released v19.0.1 that adds it.

**Comment by AnthonyGiretti** [comment]
Still not working:
![image](https://github.com/googleads/google-ads-dotnet/assets/21200167/a017510f-fe41-496e-a013-f3243ea58a5e)

![image](https://github.com/googleads/google-ads-dotnet/assets/21200167/758ce4c7-b073-4d48-a449-6be509138408)
